# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Tests and Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - id: 'auth'
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "${{ secrets.VPC_SC_WORKLOAD_IDENTITY_PROVIDER }}"
        service_account: 'ems-gcp-toolkit@sap-vpc-sc-provisioning.iam.gserviceaccount.com'
    - name: Test with pytest
      run: |
        pytest -o python_files="test_*.py"
        
    - name: Integration Test with pytest
      run: |
        pytest -o python_files="it_*.py" --disable-warnings -x
